platform :android do
    desc "Build beta"
    lane :beta do |options|
        increment_version_code(
            gradle_file_path: './android/app/build.gradle',
            version_code: sh('date +%s').to_i
        )
        gradle(task: 'clean', project_dir: './android')
        gradle(
            task: 'assemble',
            build_type: 'Release',
            project_dir: './android',
            properties: {
                "android.injected.signing.store.file" => options[:keystore_path],
                "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
                "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
                "android.injected.signing.key.password" => ENV["KEY_PASSWORD"],
            }
        )
        firebase_app_distribution(
            app: ENV["FIREBASE_APP"],
            groups: ENV["FIREBASE_DISTRIBUTION_GROUP"]
        )
    end
end

platform :ios do
    before_all do
        setup_circle_ci
      end

    desc "Build iOS beta"
    lane :beta do
        setup_ci if ENV['CI']
        app_store_connect_api_key(
            key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
            issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
            key_content: ENV["APP_STORE_CONNECT_API_KEY_KEY"]
        )
        match(
            type: 'appstore',
            readonly: is_ci
        )
        increment_build_number(
            xcodeproj: './ios/rncicd.xcodeproj',
            build_number: sh('date +%s').to_i
        )
        build_app(
            workspace: './ios/rncicd.xcworkspace',
            scheme: 'rncicd'
        )
        upload_to_testflight(
            skip_waiting_for_build_processing: true
        )
    end
end
